### PR TITLE
Display Bedrock players

### LINKED ISSUE #53: Bedrock Players are not listed
Java Players are availabale, but Bedrock (GeyserMC) players aren't listed

### PR DESCRIPTION
**Pull request by Dantevg**
Closes #53

### CODE REVIEW

**Comment by Olen** [comment]
Any chance of getting this in a release?

I made a minor fix to WebStats-dist.js just to get it to actually displaying some stats at all:
```
    static isPlayerOrServer = t => "#server" == t || t.match(/^\w{3,16}$/) && !t.match(/^\d*$/)||this.isBedrockPlayer(t);
    static isBedrockPlayer=t=>t.startsWith('.');
```

**Comment by Dantevg** [comment]
This PR is pretty old and based on older code so it will need a bit of work to get it in a working (and mergeable) state again.

I'm happy that there is some enthusiasm for getting bedrock to work, though! The primary reason that this wasn't merged is that I cannot test whether it works or not (I do not have a bedrock server). If you would be willing to test, I can probably get a version working somewhere this week.

**Comment by Olen** [comment]
I am more than happy to test it.
And the code I pasted above was only the bare minimum from the original PR that made it work (just allowing a '.' in front ot the player name).

**Comment by Dantevg** [comment]
I didn't know it was that simple :) The original PR code also included a way to change the bedrock prefix (because apparently it is configurable), but for simplicity I decided to rip out that code. Should be working as it is basically just your fix as well!

**Comment by Olen** [comment]
Do you have a test-release I can try?
Did not find an updated jar anywhere.

**Comment by Dantevg** [comment]
The latest commit has a github action that automatically builds the jar and js file. You can find it on the bottom of the [action summary page](https://github.com/Dantevg/WebStats/actions/runs/6016661578), under "Artifacts".

**Comment by Dantevg** [comment]
Damn, I thought I had tested the github actions thing properly but apparently not... For what it's worth, here's the jar including the js file: [WebStats-1.8.6-dev.zip](https://github.com/Dantevg/WebStats/files/12473730/WebStats-1.8.6-dev.zip)

**Pull request merged**
