### PR TITLE
Allow serving of favicon and logo image

### PR DESCRIPTION
**Pull request by Olen**
Not sure if this is enough (I am not that into Java).

Also not sure you want to go down the slippery slope of allowing more content to be served, but at least a favicon would be nice...

### CODE REVIEW

**Comment by Dantevg** [comment]
A favicon is a good idea indeed, thanks for the PR! (I can imagine it took some effort to find the right place through my poorly commented code haha)

I assume your intention for `logo.png` is to put a bigger logo somewhere on the page? I'm thinking that it may be better to go down that slippery slope and add a whitelist of resource files to be served to the config file.

**Comment by Olen** [comment]
Yes, my Idea was to place a bigger logo/title on the page.  I am currently hosting it on another server, so it is not a big problem, but a whitelist might be a good idea.
It could be nice to add some simple instruction pages, simple wrapper pages to e.g. maps etc., without going completely crazy and implement everything a webserver potentially can do.  So being able to serve up e.g. /help.html and /map.html with some appropriate content would be cool.

**Comment by Dantevg** [comment]
I added a config option to list additional resources. If that works for you, I'll merge this.

(I had hoped that my new github actions setup would have worked and there would be an auto-built jar available already but alas)

**Comment by Olen** [comment]
Adding a list is perfectly fine.  
I don't plan on serving a million files.  It's just a nice place to also maybe serve the server resource pack and a few images to add to the stats-page and some info/instructions/rules, to keep them all in the same place.

**Comment by Olen** [comment]
Seems to be working perfectly.  
Added a few files (some pngs and a zip) and they all downloaded and showed up as expected.
Tried a few fake paths, like "../../../../etc/passwd" etc., and they all gave a 404.

Now - I have not done a 100% secirity audit here to verify that nothing crazy can be done with it, but it looks good.

**Comment by Dantevg** [comment]
Thanks so much for the help! I reckon it would not even be bad if someone would have wanted to expose some file like that deliberately but it's nice that it gives a 404 anyway.

**Pull request merged**
